'use strict'

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      'records',
      [
        {
          artist: 'Seu Jorge',
          title: 'The Life Aquatic Studio Sessions',
          genre: 'Rock | Folk, World, & Country | Stage & Screen',
          style: 'Acoustic | MPB | Soundtrack',
          format: 'Vinyl',
          year: 2014,
          discogsId: 11313902,
          lowestPrice: 21,
          imageUrl:
            'https://img.discogs.com/H4ypuBeUAhb5qODIL-ErHgO3Oeg=/fit-in/600x594/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-11313902-1557826486-7244.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'JuJu Rogers | Bluestaeb',
          title: 'LIT - Lost In Translation',
          genre: 'Hip Hop',
          style: 'Conscious',
          format: 'Vinyl',
          year: 2016,
          discogsId: 9435492,
          lowestPrice: 9,
          imageUrl:
            'https://img.discogs.com/B16SN-IkFmBaqjNELsaArIZM1Hw=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9435492-1480535844-2368.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Pat Thomas (3) | Kwashibu Area Band',
          title: 'Obiaa!',
          genre: 'Funk / Soul | Folk, World, & Country',
          style: 'Afrobeat | Funk | Highlife | African',
          format: 'Vinyl',
          year: 2019,
          discogsId: 14225655,
          lowestPrice: 20,
          imageUrl:
            'https://img.discogs.com/d_7mCsBHz9VP9KDOCvW-ne8vUrw=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-14225655-1570226905-6311.png.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Sascha Dive',
          title: 'Down Edit',
          genre: 'Electronic',
          style: 'House | Acid | Tech House',
          format: 'Vinyl',
          year: 2007,
          discogsId: 992293,
          lowestPrice: 3,
          imageUrl:
            'https://img.discogs.com/w4YlDyb5c6Wzk4vW3IsSv62atC8=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-992293-1183718554.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Mobb Deep',
          title: 'The Infamous',
          genre: 'Hip Hop',
          style: 'Hardcore Hip-Hop',
          format: 'Vinyl',
          year: 1995,
          discogsId: 223127,
          lowestPrice: 49,
          imageUrl:
            'https://img.discogs.com/KW8mn22ymcff6XIK8EGiN8w_Bk8=/fit-in/600x602/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-223127-1344811288-6031.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Digable Planets',
          title: "Reachin' (A New Refutation Of Time And Space)",
          genre: 'Hip Hop',
          style: 'Jazzy Hip-Hop',
          format: 'Vinyl',
          year: 2018,
          discogsId: 11634867,
          lowestPrice: 39,
          imageUrl:
            'https://img.discogs.com/3kHMOc7TjYeF3m15BK3d9YQzPcQ=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-11634867-1520005885-2246.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Nu Guinea',
          title: 'Nuova Napoli',
          genre: 'Electronic | Jazz | Funk / Soul',
          style: 'Disco | Funk | Fusion | Jazz-Funk | Boogie',
          format: 'Vinyl',
          year: 2018,
          discogsId: 11600879,
          lowestPrice: 43,
          imageUrl:
            'https://img.discogs.com/RM1k7dHc08z19EUYYN-1pAMtRaM=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-11600879-1519218908-1395.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'William Onyeabor',
          title: 'Good Name',
          genre: 'Electronic | Funk / Soul',
          style: 'Funk',
          format: 'Vinyl',
          year: 2013,
          discogsId: 5159002,
          lowestPrice: 15,
          imageUrl:
            'https://img.discogs.com/x0QrDyLvcJi4vZP4vAG94YlvEeQ=/fit-in/405x405/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-5159002-1389198353-9794.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Oumou Sangare',
          title: 'Moussolou',
          genre: 'Folk, World, & Country',
          style: 'African',
          format: 'Vinyl',
          year: 2016,
          discogsId: 8395885,
          lowestPrice: 17,
          imageUrl:
            'https://img.discogs.com/g_9bpb7_Sz4wV_gcL5sl3aM2Ozc=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-8395885-1462537638-4163.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Leston Paul',
          title: "Let's Party Tonight",
          genre: 'Reggae | Funk / Soul',
          style: 'Boogie | Disco | Soca',
          format: 'Vinyl',
          year: 2018,
          discogsId: 11377288,
          lowestPrice: 16,
          imageUrl:
            'https://img.discogs.com/OiImILHBiJz3Cba5-RU-Hjr8zfM=/fit-in/600x594/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-11377288-1519301201-9126.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Shadow (11)',
          title: 'Sweet Sweet Dreams',
          genre: 'Electronic | Reggae | Funk / Soul',
          style: 'Disco | Soca | Bayou Funk | Boogie | Calypso',
          format: 'Vinyl',
          year: 2016,
          discogsId: 9477500,
          lowestPrice: 13,
          imageUrl:
            'https://img.discogs.com/uO6xQlmj8ymhpghzgLC5spqE_NE=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9477500-1481275289-7479.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Deadbeat',
          title: 'Walls And Dimensions',
          genre: 'Electronic',
          style: 'Techno | Ambient | Dub',
          format: 'Vinyl',
          year: 2015,
          discogsId: 7750707,
          lowestPrice: 16,
          imageUrl:
            'https://img.discogs.com/tuVLadfYUJ58Siz9bgLPao92mgU=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-7750707-1448023852-8454.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'James Mason',
          title: 'I Want Your Love',
          genre: 'Electronic | Funk / Soul',
          style: 'Deep House | Soul | Disco',
          format: 'Vinyl',
          year: 2012,
          discogsId: 3366766,
          lowestPrice: 8,
          imageUrl:
            'https://img.discogs.com/zGfLfLSATh-TmLz2uUlSxfrqIuI=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3366766-1386601381-2769.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Fela Kuti | Egypt 80',
          title: 'Beasts Of No Nation',
          genre: 'Jazz | Folk, World, & Country',
          style: 'Afrobeat',
          format: 'Vinyl',
          year: 2015,
          discogsId: 7629024,
          lowestPrice: 16,
          imageUrl:
            'https://img.discogs.com/1PArfvTcrlfT3p6IaM-DfpUaGbI=/fit-in/595x595/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-7629024-1462481562-4820.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          artist: 'Renegades Of Jazz',
          title: 'Moyo Wangu',
          genre: 'Electronic | Jazz | Funk / Soul',
          style: 'Afrobeat | Funk | Breakbeat | Broken Beat | Future Jazz',
          format: 'Vinyl',
          year: 2016,
          discogsId: 8954894,
          lowestPrice: 156,
          imageUrl:
            'https://img.discogs.com/T7TC7w_TxKjACtPYx3KjNxZXjuA=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-8954894-1472583490-9614.jpeg.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    )
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('records', null, {})
  },
}
